name: "Publish a flake to flakestry"
on:
  push:
    branches:
      - "nyxpkgs-unstable"
  workflow_call:
  workflow_dispatch:

jobs:
  flakestry-publish:
    runs-on: ubuntu-latest
    permissions:
      id-token: "write"
      contents: "read"
    steps:
      - name: Retrieve commit count
        run: echo "COMMITS=$(git rev-list --count nyxpkgs-unstable)" >> $GITHUB_ENV
      - uses: flakestry/flakestry-publish@main
        with:
          version: "v0.1.${{ env.COMMITS }}"
